{
 "title": "Metrics Copy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace!=\"kube-system\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tetragon errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_errors_total{}[1m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{}[1m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon dropped events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_notify_overflowed_events{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon ring buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_ringbuf_perf_event_received{}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(tetragon_ringbuf_perf_event_lost{}[1m]))",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "Tetragon maps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(tetragon_map_in_use_gauge{}) by (map, total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets count per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{image!=\"\", namespace!=\"kube-system\", namespace=~\"$namespace\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers egress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\", namespace!=\"kube-system\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon aggregated containers network egress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(tetragon_network_flows{pod_name=~\"$pod\", pod_namespace!=\"kube-system\", pod_namespace=~\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"poc\",container=\"tetragon\",image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"poc\",container=\"export-stdout\",image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}-vector-export"
    }
   ]
  },
  {
   "title": "Tetragon cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"poc\", container=\"tetragon\", image!=\"\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"poc\", container=\"export-stdout\", image!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-vector-export"
    }
   ]
  },
  {
   "title": "Vector aggregator memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"poc\",container=\"vector\",image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector aggregator cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"poc\", container=\"vector\", image!=\"\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector aggregator events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(vector_processed_events_total{}[1m])) by (component_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector discarded events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(vector_events_discarded_total{}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}